import { jsPDF } from "jspdf";
import type { StatisticsSummary } from "@/lib/analyticsApi";
import type { ReportExportContext } from "./reportExportContext";

export type ReportTableColumn = { key: string; label: string };

export type ReportIndicator = {
  label: string;
  value: string | number;
  interpretation?: string;
};

export type ChartSnapshotItem = Record<string, string | number>;

export type PredictiveAnalyticsBlock = {
  modelUsed?: string;
  regressionEquation?: string;
  forecastingMethod?: string;
  confidenceLevel?: string;
  rSquared?: string | number;
  prediction?: string;
  interpretation?: string;
};

export type ProfessionalReportPayload = {
  context: ReportExportContext;
  reportPeriod?: string;
  filtersUsed: string[];
  executiveSummary: ReportIndicator[];
  tableColumns: ReportTableColumn[];
  tableRows: Record<string, unknown>[];
  statistics?: StatisticsSummary | null;
  indicators?: ReportIndicator[];
  chartSnapshot?: {
    chartType: string;
    title: string;
    items: ChartSnapshotItem[];
    valueField?: string;
    xAxisLabel?: string;
    yAxisLabel?: string;
  };
  interpretation?: string | null;
  predictive?: PredictiveAnalyticsBlock | null;
  analyticsType?: string;
  filenameStem: string;
};

const MARGIN = 14;
const PAGE_BOTTOM = 285;
const LINE = 5.2;

type PdfWriter = {
  doc: jsPDF;
  y: number;
  pageW: number;
  ensureSpace: (mm: number) => void;
  heading: (text: string, size?: number) => void;
  subheading: (text: string) => void;
  paragraph: (text: string, size?: number) => void;
  bulletList: (items: string[]) => void;
  keyValue: (label: string, value: string) => void;
};

function createWriter(doc: jsPDF): PdfWriter {
  const pageW = doc.internal.pageSize.getWidth();
  let y = 18;

  const ensureSpace = (neededMm: number) => {
    if (y + neededMm > PAGE_BOTTOM) {
      doc.addPage();
      y = 18;
    }
  };

  const heading = (text: string, size = 12) => {
    ensureSpace(12);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(size);
    doc.setTextColor(30);
    doc.text(text, MARGIN, y);
    y += size === 12 ? 8 : 10;
  };

  const subheading = (text: string) => {
    ensureSpace(10);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(55);
    doc.text(text, MARGIN, y);
    y += 7;
  };

  const paragraph = (text: string, size = 9) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    doc.setTextColor(40);
    const lines = doc.splitTextToSize(text, pageW - MARGIN * 2);
    ensureSpace(lines.length * 4.2 + 4);
    doc.text(lines, MARGIN, y);
    y += lines.length * 4.2 + 3;
  };

  const bulletList = (items: string[]) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(40);
    for (const item of items) {
      const lines = doc.splitTextToSize(`• ${item}`, pageW - MARGIN * 2 - 4);
      ensureSpace(lines.length * 4.2 + 2);
      doc.text(lines, MARGIN + 2, y);
      y += lines.length * 4.2 + 1.5;
    }
    y += 2;
  };

  const keyValue = (label: string, value: string) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    const labelText = `${label}:`;
    const labelW = doc.getTextWidth(labelText);
    ensureSpace(LINE + 2);
    doc.text(labelText, MARGIN, y);
    doc.setFont("helvetica", "normal");
    const valueLines = doc.splitTextToSize(value || "—", pageW - MARGIN * 2 - labelW - 3);
    doc.text(valueLines, MARGIN + labelW + 2, y);
    y += Math.max(valueLines.length * LINE, LINE) + 1;
  };

  return { doc, y, pageW, ensureSpace, heading, subheading, paragraph, bulletList, keyValue };
}

function writeStandardHeader(w: PdfWriter, payload: ProfessionalReportPayload) {
  const { context, reportPeriod, filtersUsed } = payload;
  const generated = context.generatedAt;
  const dateStr = generated.toLocaleDateString("en-PH", {
    timeZone: "Asia/Manila",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const timeStr = generated.toLocaleTimeString("en-PH", {
    timeZone: "Asia/Manila",
    hour: "numeric",
    minute: "2-digit",
  });
  const exportTs = generated.toISOString();

  w.doc.setFont("helvetica", "bold");
  w.doc.setFontSize(14);
  w.doc.setTextColor(20);
  w.doc.text(context.systemName, MARGIN, w.y);
  w.y += 8;

  w.doc.setDrawColor(180);
  w.doc.line(MARGIN, w.y, w.pageW - MARGIN, w.y);
  w.y += 7;

  w.keyValue("Report", payload.context.reportName);
  w.keyValue("Module", context.moduleName);
  w.keyValue("Generated by", context.generatedBy);
  w.keyValue("Role", context.userRole);
  w.keyValue("Generated date", dateStr);
  w.keyValue("Generated time", timeStr);
  w.keyValue("Report period", reportPeriod ?? "All available data");
  w.keyValue("System version", context.systemVersion);
  w.keyValue("Export timestamp", exportTs);

  w.subheading("Filters used");
  w.bulletList(filtersUsed);

  w.y += 2;
  w.doc.setDrawColor(220);
  w.doc.line(MARGIN, w.y, w.pageW - MARGIN, w.y);
  w.y += 8;
}

function writeExecutiveSummary(w: PdfWriter, items: ReportIndicator[]) {
  w.heading("Section 1 — Executive Summary");
  if (!items.length) {
    w.paragraph("No summary metrics available for this export.");
    return;
  }
  for (const item of items) {
    w.keyValue(item.label, String(item.value));
    if (item.interpretation) w.paragraph(item.interpretation, 8);
  }
  w.y += 3;
}

function writeFilterSummary(w: PdfWriter, filters: string[]) {
  w.heading("Section 2 — Filter Summary");
  w.bulletList(filters);
}

function formatCell(value: unknown): string {
  if (value == null || value === "") return "—";
  if (typeof value === "number" && Number.isFinite(value)) {
    return Number.isInteger(value) ? String(value) : value.toFixed(2);
  }
  return String(value);
}

function writeDataTable(
  w: PdfWriter,
  columns: ReportTableColumn[],
  rows: Record<string, unknown>[],
) {
  w.heading("Section 3 — Main Data Table");
  w.paragraph(`Total records: ${rows.length}`);

  if (!rows.length || !columns.length) {
    w.paragraph("No tabular data available for this report.");
    return;
  }

  const colCount = Math.min(columns.length, 6);
  const usableCols = columns.slice(0, colCount);
  const colW = (w.pageW - MARGIN * 2) / colCount;
  const maxRowsPerPage = Math.floor((PAGE_BOTTOM - w.y - 20) / 5.5);

  const drawHeader = () => {
    w.ensureSpace(12);
    w.doc.setFillColor(240, 240, 240);
    w.doc.rect(MARGIN, w.y - 4, w.pageW - MARGIN * 2, 7, "F");
    w.doc.setFont("helvetica", "bold");
    w.doc.setFontSize(7.5);
    usableCols.forEach((col, i) => {
      const cell = col.label.slice(0, 18);
      w.doc.text(cell, MARGIN + i * colW + 1, w.y);
    });
    w.y += 6;
  };

  drawHeader();
  let rowOnPage = 0;

  for (let ri = 0; ri < rows.length; ri++) {
    if (rowOnPage >= maxRowsPerPage) {
      w.doc.addPage();
      w.y = 18;
      drawHeader();
      rowOnPage = 0;
    }
    w.ensureSpace(6);
    w.doc.setFont("helvetica", "normal");
    w.doc.setFontSize(7);
    usableCols.forEach((col, i) => {
      const raw = formatCell(rows[ri][col.key]);
      const clipped = raw.length > 22 ? `${raw.slice(0, 21)}…` : raw;
      w.doc.text(clipped, MARGIN + i * colW + 1, w.y);
    });
    w.y += 5;
    rowOnPage++;
  }

  if (columns.length > colCount) {
    w.paragraph(
      `Note: ${columns.length - colCount} additional column(s) omitted from PDF layout. Export CSV for full columns.`,
      7.5,
    );
  }
  w.y += 4;
}

function writeStatistics(w: PdfWriter, stats: StatisticsSummary | null | undefined) {
  w.heading("Section 4 — Statistical Summary");
  if (!stats) {
    w.paragraph("Insufficient numeric data for statistical analysis.");
    return;
  }
  w.keyValue("Count", String(stats.count));
  w.keyValue("Minimum", String(stats.minimum));
  w.keyValue("Maximum", String(stats.maximum));
  w.keyValue("Average", String(stats.average));
  w.keyValue("Median", String(stats.median));
  w.keyValue("Subtotal / Sum", String(stats.subtotal));
  if (stats.standard_deviation != null) {
    w.keyValue("Standard deviation", String(stats.standard_deviation));
    const variance = stats.standard_deviation ** 2;
    w.keyValue("Variance", variance.toFixed(2));
  }
  if (stats.insufficient_for_spread) {
    w.paragraph("Spread metrics require at least two numeric observations.");
  }
  w.y += 3;
}

function numericFromItem(item: ChartSnapshotItem, valueField?: string): number {
  const keys = valueField
    ? [valueField]
    : ["value", "amount_php", "count", "revenue_php", "total_cost_php"];
  for (const k of keys) {
    const v = item[k];
    const n = Number(v);
    if (Number.isFinite(n)) return n;
  }
  return 0;
}

function labelFromItem(item: ChartSnapshotItem): string {
  const keys = ["label", "status", "client_name", "truck_code", "driver_name", "route", "month", "period"];
  for (const k of keys) {
    if (item[k] != null && String(item[k]).trim()) return String(item[k]).slice(0, 24);
  }
  return "Item";
}

function writeChartSnapshot(
  w: PdfWriter,
  snapshot: NonNullable<ProfessionalReportPayload["chartSnapshot"]>,
) {
  w.heading("Section 5 — Visualization Snapshot");
  w.paragraph(`${snapshot.title} (${snapshot.chartType.toUpperCase()})`);
  if (snapshot.xAxisLabel) w.keyValue("X-axis", snapshot.xAxisLabel);
  if (snapshot.yAxisLabel) w.keyValue("Y-axis", snapshot.yAxisLabel);

  const items = snapshot.items.slice(0, 12);
  if (!items.length) {
    w.paragraph("No chart data points available.");
    return;
  }

  const values = items.map((it) => numericFromItem(it, snapshot.valueField));
  const maxVal = Math.max(...values, 1);
  const barMaxW = w.pageW - MARGIN * 2 - 55;
  const barH = 4.5;

  w.ensureSpace(items.length * (barH + 3) + 8);
  items.forEach((item, idx) => {
    const label = labelFromItem(item);
    const val = values[idx];
    const barW = (val / maxVal) * barMaxW;
    w.doc.setFont("helvetica", "normal");
    w.doc.setFontSize(7.5);
    w.doc.text(label, MARGIN, w.y);
    const barY = w.y - 3;
    w.doc.setFillColor(82, 183, 136);
    w.doc.rect(MARGIN + 52, barY, barW, barH, "F");
    w.doc.setTextColor(60);
    w.doc.text(String(val), MARGIN + 54 + barW + 2, w.y);
    w.y += barH + 3;
  });
  w.y += 4;
}

function writeInterpretation(w: PdfWriter, interpretation: string | null | undefined, analyticsType?: string) {
  w.heading("Section 6 — Analytics Interpretation");
  if (analyticsType) w.keyValue("Analytics type", analyticsType);
  if (interpretation?.trim()) {
    w.paragraph(interpretation);
  } else {
    w.paragraph(
      "No AI interpretation was generated for this export. Use descriptive statistics and trend indicators above for panel review.",
    );
  }
}

function writePredictiveBlock(w: PdfWriter, block: PredictiveAnalyticsBlock) {
  w.subheading("Predictive analytics details");
  if (block.modelUsed) w.keyValue("Model used", block.modelUsed);
  if (block.regressionEquation) w.keyValue("Regression equation", block.regressionEquation);
  if (block.forecastingMethod) w.keyValue("Forecasting method", block.forecastingMethod);
  if (block.confidenceLevel) w.keyValue("Confidence level", block.confidenceLevel);
  if (block.rSquared != null) w.keyValue("R²", String(block.rSquared));
  if (block.prediction) w.keyValue("Prediction", block.prediction);
  if (block.interpretation) w.paragraph(block.interpretation);
}

function writeFooter(w: PdfWriter) {
  const pages = w.doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    w.doc.setPage(p);
    w.doc.setFont("helvetica", "normal");
    w.doc.setFontSize(8);
    w.doc.setTextColor(120);
    const footer = `FleetOpts Report · Page ${p} of ${pages} · Generated ${new Date().toLocaleString("en-PH", { timeZone: "Asia/Manila" })} PHT`;
    w.doc.text(footer, MARGIN, 292);
  }
}

export function downloadProfessionalReportPdf(payload: ProfessionalReportPayload): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const w = createWriter(doc);

  writeStandardHeader(w, payload);
  writeExecutiveSummary(w, payload.executiveSummary);
  writeFilterSummary(w, payload.filtersUsed);
  writeDataTable(w, payload.tableColumns, payload.tableRows);
  writeStatistics(w, payload.statistics);

  if (payload.chartSnapshot?.items?.length) {
    writeChartSnapshot(w, payload.chartSnapshot);
  }

  writeInterpretation(w, payload.interpretation, payload.analyticsType);

  if (payload.predictive) {
    writePredictiveBlock(w, payload.predictive);
  }

  if (payload.indicators?.length) {
    w.heading("Supplementary Indicators");
    for (const ind of payload.indicators) {
      w.keyValue(ind.label, String(ind.value));
      if (ind.interpretation) w.paragraph(ind.interpretation, 8);
    }
  }

  writeFooter(w);

  const stem = payload.filenameStem.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 80);
  doc.save(`fleetopts-${stem}.pdf`);
}
